language: node_js
notifications:
  email: false
node_js:
- 8.9.1
- 10
sudo: required
cache:
  directories:
  - node_modules
git:
  submodules: false
before_install:
- echo 'Asia/Tokyo' | sudo tee /etc/timezone
- npm i gulp-cli -g
- gulp --version
script:
- gulp prebuild-files
- gulp