language: node_js
notifications:
  email: false
node_js:
- 7.10.0
sudo: required
cache:
  directories:
  - node_modules
git:
  submodules: false
before_install:
- echo 'Asia/Tokyo' | sudo tee /etc/timezone
- npm i grunt -g
- grunt --version
script:
- grunt